### ISSUE TITLE
Upload job does not finish when uploading large datasets

### ISSUE THREAD

**Issue by B-Hartmann** [DCOR-dev/dcor-docs#2]
DCOR-Aid 0.8.3

When uploading large datasets to DCOR, let's say file size 17 GB, the file upload seems to be fast (depending on the internet connection), but then it gets stuck in the following state:

![DCOR-Aid_0-8-3_upload_of_big_datasets_does_not_finish](https://user-images.githubusercontent.com/75362246/143906536-9fbef189-f5d9-4190-bdee-9b6c9a4c1edc.PNG)

So, the transfer is done according to DCOR-Aid (100 % shown), but it doesn't continue to upload other resources of that dataset or finish the task by verifying it. On the website, I can see for many hours (estimated, ca. 6 hrs) that the dataset still doesn't contain any resources. It seems that the server needs a long time until the file is processed and the rtdc file actually appears as a resource on the website. But even then, DCOR-Aid doesn't continue the upload task.  
So I would need to restart DCOR-Aid, it then realizes that one resource was already uploaded, it continues with the remaining ones, and eventually verifies the datasets and finishes the task.

It doesn't seem to happen with files that are 100 MB to 1 GB, but I cannot say where the threshold is.

EDIT: Changed the time the server needs until the dataset shows up on the website from 10 hrs to 6 hrs because that is actually how long it took for the dataset in the picture.

**Comment by paulmueller** [comment]
Transferring to dcor-docs, because this can only be resolved using nginx/uWSGI configuration.

**Comment by paulmueller** [comment]
@B-Hartmann Could you please retry large file uploads? DCOR-Aid should hang no more than 30mins now after reaching 100% transfer.

**Comment by B-Hartmann** [comment]
I tried another upload of a large file (roughly 15 GB). The upload took 6 minutes and after another 20 minutes in "transfer 100 %", it verified and finished the upload task. Looks good!
